apiVersion: apps/v1
kind: DaemonSet
metadata:
 name: nginx-deployment
 labels:
    k8s-app: fluentd-logging
spec:
 selector:
   matchLabels:
     app: nginx 
 replicas: 1 
 strategy:
   type: RollingUpdate
   rollingUpdate:
     maxSurge: 50%
     maxUnavailable: 25%
 template: 
   metadata:
     labels:
       app: nginx
   spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: type
                operator: In
                values:
                - type=external_facing
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: node.kubernetes.io/instance-type
                operator: In
                values:
                - t4.xlarge
          - weight: 2
            preference:
              matchExpressions:
              - key: node.kubernetes.io/instance-type
                operator: In
                values:
                - t3.large
      containers:
        - name: nginx
          image: nginx:1.7.9
          ports:
          - containerPort: 80

