# Create the file pod-storage.yaml
# kubectl apply -f pod-storage.yaml
# kubectl exec -ti redis -c redis -- bash
# kubectl exec -ti redis -c springapp -- bash

apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
    yaniv: fe-v1
spec:
  containers:
  - name: redis
    image: redis:latest
    volumeMounts:
    - name: hostpathvolume
      mountPath: /storage
  - name: springapp
    image: yanivomc/spring-music:latest
    volumeMounts:
    - name: hostpathvolume
      mountPath: /sotrage
  volumes:
  - name: hostpathvolume
    hostPath:
       path: /data



