apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend
  labels:
    app: spring
    tier: fe
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: frontend
  template:   # here we define our PODS Specs (k8s uses go template in the background)
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: app1
        image: supergiantkir/animals:bear
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /storage
          name: app-storage
      - name: app2
        image: yanivomc/spring-music:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /storage
          name: app-storage
      volumes:
      - name: app-storage
        hostPath:
          # directory location on host
          path: /tmp/files
          # this field is optional
          type: DirectoryOrCreate
