database_prod: 
  dbname: db_mysql
  dbtable: music
database_test: 
  dbname: db_mysql-test
  dbtable: music
pods: 
  image: spring-music
  repo: yanivomc
  tag: latest
food:
  drink: tea
  eat: Peanut Butter and Jelly sandwich 
service:
  type: LoadBalancer
deployment:
  replica: 2
  cont_name: spring-music
  image: yanivomc/spring-music:latest
