apiVersion: v1
kind: Pod
metadata:
  name: podspecandvols
  labels:
    name: podspecandvols
spec:
  containers:
  - name: app1
    image: supergiantkir/animals:bear
    resources:
      limits:
        memory: 128Mi
        cpu: 500m
    volumeMounts:
      - mountPath: "/storage"
        name: app-storage
    # ports:
    #   - containerPort: <Port>  
  - name:  app2
    image:  yanivomc/spring-music:latest
    resources:
      limits:
        memory: 128Mi
        cpu: 500m
    volumeMounts:
      - mountPath: "/storage"
        name: app-storage
  volumes:
    - name: app-storage
      hostPath:
        path:  "/tmp/files"
        type: DirectoryOrCreate