apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name | quote }} #from RELEASE NAME
spec:
  selector: 
    matchLabels:
      app: {{ .Values.app.name | indent 6 }}   
  replicas: {{ .Values.replica.no }} 
  template:
    metadata:
      labels:
        app: {{ .Values.app.name | indent 8 }} 
    spec:
      containers:
      - name: {{ .Values.name }}  #from values
        image: yanivomc/spring-music:latest #from values
        ports:
        - containerPort: {{ default 8080 .Values.port }} 

