apiVersion: v1
kind: Service
metadata:
  name:  bear-svc
  namespace: igor
  labels:
    app: animals
    animal: bear
spec:
  selector:
    animal: bear
  type:  ClusterIP
  ports:
  - name:  web
    port:  80
    targetPort:  80