apiVersion: v1
kind: Service
metadata:
  name:  moose-svc
  namespace: igor
  labels:
    app: animals
    animal: moose
spec:
  selector:
    animal: moose
  type:  ClusterIP
  ports:
  - name:  web
    port:  80
    targetPort:  80