apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-spring-music 
  labels:
  app: {{ .Values.appname}}
  version: 1  
spec:
  selector: 
    matchLabels:
      app: music  
  replicas: {{ .Values.appenv.replicas }}
  template:
    metadata:
      labels:
        app: music
    spec:
      containers:
      - name:  {{ .Values.appname }}
        image: {{ .Values.appenv.image }}:{{ .Values.appenv.imagetag }}
        ports:
        - containerPort: {{ .Values.appenv.targetPort }}
