apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-music-deployment
spec:
  selector:
    matchLabels:
      app: spring-music
  replicas: 1 
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 25%
  template: 
    metadata:
      labels:
        app: spring-music
    spec:
      nodeSelector:
        type: external_facing
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: topology.kubernetes.io/region
      containers:
      - name: spring-music
        image: yanivomc/spring-music:latest
        ports:
        - containerPort: 80
