services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 5

  etl:
    build: .
    environment:
      DB_USER: user
      DB_PASS: password
      DB_HOST: db
      DB_NAME: mydb
    depends_on:
      db:
        condition: service_healthy
    mem_limit: 512m
    cpus: 0.5

volumes:
  db_data:
