apiVersion: v1
kind: Pod
metadata:
  name: redis
spec:
  containers:
  - name: bear-app
    image: supergiantkir/animals:bear
    volumeMounts:
    - name: app-storage
      mountPath: /storage
  - name: spring-music
    image: yanivomc/spring-music:latest
    volumeMounts:
    - name: app-storage
      mountPath: /storage
  volumes:
    - name: app-storage  
      hostPath:
       path:  /storage
       type: DirectoryOrCreate
      
