apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  labels:
{{- include "spring.labels" . | nindent 3}}
data:
  dbname: {{ .Values.dbname }}
  dbtable: {{ .Values.dbtable }}