apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: {{.Values.cronjob.schedule}}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: {{.Values.pods.image}}
            imagePullPolicy: IfNotPresent
            command: 
            - /bin/sh
            - -c
            - date; echo {{.Values.cronjob.output}}
          restartPolicy: OnFailure