kind: Service     
apiVersion: v1     
metadata:
  name: {{ .Release.Name }}
spec:
  selector:
    app: music    
  type: {{ .Values.service.type }}
  ports:         
  - name: http   
    protocol: TCP
    port: 80
    targetPort: 8080
