apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend
  labels:
    app: fe
spec:
  replicas: 3
  selector: 
    matchLabels: 
      tier: redis
  template:
    metadata:
      labels: 
        tier: redis
    spec:
      containers:
        - name: app1
          image: supergiantkir/animals:bear
          volumeMounts:
            - name: app-storage
              mountPath: /storage
        - name: app2
          image: yanivomc/spring-music:latest
          volumeMounts:
            - name: app-storage
              mountPath: /storage
      volumes:
        - name: app-storage
          hostPath: 
            path: /tmp/files
            type: DirectoryOrCreate
