apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: elastic-search
spec:
  replicas: 2
  selector: 
    matchLabels: 
      app: elastic-app
  template:
    metadata:
      labels: 
        app: elastic-app
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: NotIn
                values:
                - elastic-app
            topologyKey: "labels"
      containers:
        - name: app1
          image: quay.io/pires/docker-elasticsearch-kubernetes:6.2.4