apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: {{ .Values.jobs.image }}
            imagePullPolicy: IfNotPresentkub
            command: ["/bin/sh", "-c", "echo hello world"]
          restartPolicy: OnFailure