apiVersion: apps/v1
kind: Deployment
metadata:
  name: bear
  labels:
    app: animal
spec:
  selector:
    matchLabels:
      app: animal
  strategy:
    type: Recreate
  replicas: 1
  template: 
    metadata:
      labels:
        app: animal
    spec:
      containers:
      - name: animal
        image: supergiantkir/animals:bear
        ports:
        - containerPort: 80
