database_prod: 
  dbname: db_mysql
  dbtable: music
database_test: 
  dbname: db_mysql-test
  dbtable: music
pods: 
  image: yanivomc/spring-music
  tag: latest
cronjob:
  output: "Hello World"
  schedule: "* * * * *"
appName: spring-music
command: ["echo", "Hello World"]
localserviceType: NodePort
ENV: LOCAL
serviceLocalType: NodePort
serviceCloudType: LoadBalancer
replicas: 1

food:
  drink: beer
  eat: Peanut Butter and Jelly Sandwich