apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-{{ .Chart.Version }}-music
  labels:
    {{- include "labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.appname }}
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        {{- include "labels" . | nindent 12 }}
    spec:
      containers:
      - name: {{ .Values.appname }}
        image: {{ .Values.image.image }}:{{ .Values.image.tag }}
        ports:
        - containerPort: {{ .Values.service.targetPort }}

