apiVersion: apps/v1
kind: Deployment
metadata:
  name: hare-deploy
  labels:
    app: animals
spec:
  replicas: 2
  selector:
    matchLabels:
      app: animals
  template:
    metadata:
      labels:
        app: animals
    spec:
      containers:
      - name: hare-deploy
        image: supergiantkir/animals:hare
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bear-deploy
  labels:
    app: animals
spec:
  replicas: 1
  selector:
    matchLabels:
      app: animals
  template:
    metadata:
      labels:
        app: animals
    spec:
      containers:
      - name: animals 
        image: supergiantkir/animals:bear
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: animal-service
spec:
  type: LoadBalancer
  selector:
    app: animals
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
