apiVersion: apps/v1
kind: Deployment
metadata:
  name: moose-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: animals-moose
  template:
    metadata:
      labels:
        app: animals-moose
    spec:
      containers:
      - name: moose
        image: supergiantkir/animals:moose
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bear-deploy
  labels:
    app: animals
spec:
  replicas: 1
  selector:
    matchLabels:
      app: animals-bear
  template:
    metadata:
      labels:
        app: animals-bear
    spec:
      containers:
      - name: bear
        image: supergiantkir/animals:bear
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: moose-svc
spec:
  type: ClusterIP
  selector:
    app: animals-moose
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: bear-svc
spec:
  type: ClusterIP
  selector:
    app: animals-bear
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
