apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: yanivomc/spring-music:latest
        ports:
        - containerPort: 8080
---
kind: Service      # Create new service
apiVersion: v1     
metadata:
  name: my-service # Name of the service
spec:
  type: LoadBalancer
  selector:
    app: nginx    # Run on any pod(s) with label - app: myapp
  ports:          # Map incoming port to target port
  - name: http-web    # Setting multiple ports listterns 
    protocol: TCP
    port: 80
    targetPort: 8080
