version: '3.8'

services:
  app:
    build: .
    depends_on:
      - redis
    networks:
      - app_network

  redis:
    image: redis:latest
    networks:
      - app_network

  nginx:
    image: nginx:latest
    depends_on:
      - app
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
