apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  dbname: {{ .Values.database_test.dbname }}
  dbtable: {{ .Values.database_test.dbtable | upper | quote }}
  image: {{ .Values.pods.repo}}/{{ .Values.pods.image}}:{{ .Values.pods.tag}}
  drink: {{ .Values.food.drink | upper }}
  eat: {{ .Values.food.eat | upper | trunc 13 | quote}}