
# Default values for configuration of a dev demo
# see values.yaml for explanation on each params
context: &context
  scope: startx
  cluster: default
  environment: demo
  component: istio
  app: manpage
  version: "0.0.1"
html:
  namespace: demo-istio
  expose:
    enabled: true
  version: "alpine3"
  replicas: 1
  data: |
    index.html: |-
      <!DOCTYPE html>
      <html lang="en-us">
        <head>
          <title>Manpage of the istio demo</title>
        </head>
        <body>
          <h1>Manpage of the istio demo</h1> 
          <h2>Purpose of this demo</h2> 
          <p>
            The purpose of this demo is to show you how istio API management work and how
            it can help you dealing with API Management challenges.
          </p> 
          <h2>Installing this demo</h2> 
          <h3>Requirements</h3> 
          <h4>STARTX cluster manager (SXCM)</h4> 
          <p>
           Installing your cluster with <a href="https://sxcm.readthedocs.io/en/latest/" target="_blank" alt="STARTX SXCM">STARTX SXCM</a>
            Allow you to instanciate this demo as well as its requirements. 
            You can follow <a href="https://sxcm.readthedocs.io/en/latest/1-installation/" target="_blank" alt="SXCM installation docs">SXCM installation guide</a>
            and <a href="https://sxcm.readthedocs.io/en/latest/2-cluster-management/" target="_blank" alt="SXCM cluster creation docs">SXCM cluster management</a> 
            for a complete guideline on how to deploy an SXCM-managed cluster. 
          </p> 
          <h4>SXCM Cluster-service</h4> 
          <p>Install the istio cluster service. This cluster service is based on the <a href="https://artifacthub.io/packages/helm/startx/cluster-istio" target="_blank" alt="startx cluster-istio Helm-chart">STARTX cluster-istio Helm-chart</a>.</p> 
          <code>sxcm resource enable istio</code>
          <h3>Initialize this demo</h3> 
          <p>Start the demo context with the following command :</p> 
          <code>sxcm demo run istio begin</code>
          <h2>Running the demo scenario</h2> 
          <h3>Step 1</h3> 
          <p>Run first step with the following command :</p> 
          <code>sxcm demo run istio step 1</code>
          <p>
            You should go to the Developper perspective view, &gt; Topology menu of the Openshift console.
            You will observe the deployed application components. 
            Observe the route exposed in namespace <strong>startx-istio</strong>.
            IngressGataway route is your entrypoint for consulting the demo application.     
          </p> 
          <p>
            URL endpoint are :
            <ul>
              <li>&lt;ingressgateway-utl&gt;/</li>  
              <li>&lt;ingressgateway-utl&gt;/login</li>  
              <li>&lt;ingressgateway-utl&gt;/logout</li>  
              <li>&lt;ingressgateway-utl&gt;/productpage</li>  
              <li>&lt;ingressgateway-utl&gt;/api/v1/products</li>   
            </ul> 
          </p> 
          <h3>Step 2</h3> 
          <p>Run second step with the following command :</p> 
          <code>sxcm demo run istio step 2</code>
          <h2>Finishing this demo</h2> 
          <p>Cleanup the demo context with the following command :</p> 
          <code>sxcm demo run istio end</code>
        </body>
      </html>
