apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  dbname: {{ .Values.database.dbname }}
  btable: {{ .Values.database.dbtable }}
food:
  drink: {{ .Values.drink | quote | upper}}
  eat: {{ .Values.food  }}
