apiVersion: v1
kind: Service
metadata:
  name: spring-music-service
  labels:
{{ include "spring.labels" . | indent 5 }}
spec:
 ### ADD IF ENV=LOCAL > TYPE:NODEPORT ELSE > 
{{ if eq .Values.service.env "WEB" }}
  type: LoadBalancer
{{ end }}
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    {{ include "spring.labels" . | indent 5 }}
    ##name: spring-music2
