apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-music
spec:
  selector:
    matchLabels:
      app: {{ .Values.appname }}
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        app: {{ .Values.appname }}
    spec:
      containers:
      - name: {{ .Values.appname }}
        image: {{ .Values.image.image }}
        resources:
          limits:
            memory: "2Gi"
            cpu: "500m"
        ports:
        - containerPort: {{ .Values.service.targetPort }}

