dbname: "db_mysql"
dbtable: "music"
image: "yanivomc/spring-music"
tag: "latest"
database-prod: 
  dbname: db_mysql
  dbtable: music
database-test: 
  dbname: db_mysql-test
  dbtable: music
pods: 
  image: yanivomc/spring-music

