version: '3' 
services: 
  web: 
   build: . 
   ports: 
     - 8080:8080
   networks: 
     - app_layer
     - db_layer
   healthcheck:
    test: ["curl","http://localhost:8080"]
    interval: 5s
    retries: 20
    start_period: 5s

  
  
  db_mysql:
    image: wangxian/alpine-mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=music
    ports:
      - 3302:3306
    networks:
      - db_layer
    healthcheck:
      test: ["curl","http://localhost:3306"]
      interval: 5s
      retries: 20
      start_period: 5s

networks: 
 db_layer:
  driver: bridge
 app_layer:
  driver: bridge
