
{{- $appName := include "startx.appName" . -}}
{{- $namespace := .Values.html.namespace | default $appName -}}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ $appName }}-app
  namespace: {{ $namespace | quote }}
  labels:
    app.kubernetes.io/name: "{{- $appName -}}-{{- include "startx.appVersion" . -}}-app-cm"
    {{- include "example-html.labels" . | nindent 4 }}
  annotations:
    {{- include "example-html.annotations" . | nindent 4 }}
data:
  SX_ID: {{ $appName }}-app
  SX_TYPE: app
  SX_COMPONENT: {{ include "startx.appComponent" . | quote }}
  SX_NAME: Startx {{ include "startx.appComponent" . }} application
  SX_SUMMARY: Startx {{ include "startx.appComponent" . }} application based on html container
  SX_VERSION: {{ include "startx.appEnvironment" . }}
  SX_DEBUG: "false"
  EXAMPLE_VALUE: "{{- if .Values.exampleValue }}{{ .Values.exampleValue }}{{- else }}default value form chart template{{- end }}"
