{{- $appName := include "startx.appName" . -}}
{{- $namespace := .Values.html.namespace | default $appName -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $appName | quote }}
  namespace: {{ $namespace | quote }}
  labels:
    app.kubernetes.io/name: "{{- $appName -}}-{{- include "startx.appVersion" . -}}-deployment"
    {{- include "example-html.labels" . | nindent 4 }}
    kube-monkey/enabled: enabled
    kube-monkey/identifier: {{ include "startx.appName" . | default "cluster" | quote }}
  annotations:
    {{- include "example-html.annotations" . | nindent 4 }}
    checksum/config: {{ include (print $.Template.BasePath "/cm-lib.yaml") . | sha256sum }}
    argocd.argoproj.io/sync-wave: "30"
spec:
  replicas: {{ .Values.html.replicas | default 0 }}
  selector:
    matchLabels:
      app: {{ $appName }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "{{ $appName }}-{{ include "startx.appVersion" . }}-pod"
        {{- include "example-html.labels" . | nindent 8 }}
        app: {{ $appName }}
        kube-monkey/enabled: enabled
        kube-monkey/identifier: {{ include "startx.appName" . | default "cluster" | quote }}
      annotations:
        {{- include "example-html.annotations" . | nindent 8 }}
    spec: 
      containers:
        - name: application
          image: "quay.io/startx/apache:{{- .Values.html.version | default "alpine3" }}"
          command:
            - "/bin/sx-apache"
          args:
            - run
          env:
            - name: SX_VERBOSE
              value: "true"
          envFrom:
            - configMapRef:
                name: {{ $appName }}-app
          ports:
            - containerPort: 8080
              protocol: TCP
          livenessProbe:
            exec:
              command:
                - "/bin/sx-apache"
                - isLive
            initialDelaySeconds: 1
            timeoutSeconds: 3
            periodSeconds: 15
            successThreshold: 1
            failureThreshold: 2
          readinessProbe:
            exec:
              command:
                - "/bin/sx-apache"
                - isReady
            initialDelaySeconds: 2
            timeoutSeconds: 3
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 2
          resources:
            requests:
              cpu: "10m"
              memory: "64Mi"
            limits:
              cpu: "50m"
              memory: "128Mi"
          terminationMessagePath: "/dev/termination-log"
          imagePullPolicy: Always
          volumeMounts:
            - name: "apache-deploy-log"
              mountPath: "/var/log/httpd"
            - name: apache-deploy-conf
              mountPath: "/app"
              readOnly: true
      volumes:
        - name: "apache-deploy-log"
          emptyDir:
            medium: ""
        - name: apache-deploy-conf
          configMap:
            name: "{{ $appName }}-lib"
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
