{{- if .Values.html.expose -}}{{- if .Values.html.expose.enabled -}}
{{- $appName := include "startx.appName" . -}}
{{- $namespace := .Values.html.namespace | default $appName -}}
apiVersion: "route.openshift.io/v1"
kind: Route
metadata:
  name: {{ $appName | quote }}
  namespace: {{ $namespace | quote }}
  labels:
    app.kubernetes.io/name: "{{- $appName -}}-{{- include "startx.appVersion" . -}}-route"
    {{- include "example-html.labels" . | nindent 4 }}
    app: {{ $appName | quote }}
  annotations:
    {{- include "example-html.annotations" . | nindent 4 }}
    haproxy.router.openshift.io/balance: roundrobin
    haproxy.router.openshift.io/disable_cookies: "true"
    template.openshift.io/expose-uri: "http://{.spec.host}{.spec.path}"
    argocd.argoproj.io/sync-wave: "30"
spec:
  tls:
    insecureEdgeTerminationPolicy: Allow
    termination: edge
  wildcardPolicy: None
  to:
    kind: Service
    name: {{ $appName | quote }}
    weight: 100
{{- end -}}{{- end -}}
