services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3.12-management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      retries: 5

  producer:
    build: .
    command: python producer.py
    depends_on:
      rabbitmq:
        condition: service_healthy
    mem_limit: 128m
    cpus: 0.25

  etl:
    build: .
    command: python etl.py
    environment:
      DB_USER: user
      DB_PASS: password
      DB_HOST: db
      DB_NAME: mydb
      MQ_HOST: rabbitmq
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    mem_limit: 512m
    cpus: 0.5

volumes:
  db_data:
