database_prod: 
  dbname: db_mysql
  dbtable: music
database_test: 
  dbname: db_mysql-test
  dbtable: music
food:
  drink: beer
  eat: Peanut Butter and Jelly Sandwich
appname: piyush-spring
appenv:
  image: yanivomc/spring-music
  replicas: 1
  imagetag: latest
  port: 80
  targetPort: 8080
svc_type: LoadBalancer
