apiVersion: v1
kind: Service
metadata:
  name:  animals-service
  namespace: igor
  labels:
    app: animals
spec:
  selector:
    app: animals
  type:  LoadBalancer
  ports:
  - name:  web
    port:  80
    targetPort:  80