version: '3' 
services: 
  web: 
   build: ./roles/web/
   ports: 
     - 8080:8080
   networks: 
     - app_layer
   entrypoint: 
     - java 
     - -jar 
     - -Dspring.profiles.active=mysql 
     - /code/spring-music.jar
     
  db_mysql:
    image: wangxian/alpine-mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=music
    ports:
      - 3302:3306
    networks:
      - app_layer


networks: 
 app_layer:
  driver: bridge
