apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: {{.Values.job.image}}
            imagePullPolicy: IfNotPresent
            command:
            {{ include "jobcommand" . | nindent 2}}
          restartPolicy: OnFailure