apiVersion: v1
kind: Service
metadata:
  name: spring-music
  labels:
  {{ include "spring.labels" . | nindent 4 }}
spec:
  selector:
    app-name: {{ .Chart.Name }}
  {{ if eq .Values.env "local" }}
  type: NodePort
  {{ else }}
  type: LoadBalancer
  {{ end }}
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
