apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-music
spec:
  selector: 
    matchLabels:
      app: music  
  replicas: {{ .Values.appenv.replicas }}
  template:
    metadata:
      labels:
        app: music
    spec:
      containers:
      - name: {{ .Values.appname }}
        image: yanivomc/spring-music:{{ .Values.appenv.imagetag }}
        ports:
        - containerPort: {{ .Values.appenv.targetPort }}
