apiVersion: v1
kind: Pod
metadata:
  name: volumes-pod
spec:
  containers:
  - name: app1
    image: supergiantkir/animals:bear
    ports:
    - containerPort: 80
    volumeMounts:
    - mountPath: /storage
      name: app-storage
  - name: app2
    image: yanivomc/spring-music:latest
    ports:
    - containerPort: 80
    volumeMounts:
    - mountPath: /storage
      name: app-storage
  volumes:
  - name: app-storage
    hostPath:
      # directory location on host
      path: /tmp/files
      # this field is optional
      type: DirectoryOrCreate
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-storage
  labels:
    app: multiple
spec:
  containers:
  - name: app1
    image: supergiantkir/animals:bear
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
    volumeMounts:
    - mountPath: /storage
      name: app-storage
  - name: app2
    image: yanivomc/spring-music:latest
    ports:
    - containerPort: 80
  volumes:
  - name: app-storage
    hostPath:
      # directory location on host
      path: /tmp/files
      # this field is optional
      type: DirectoryOrCreate
      



