apiVersion: v1 # K8S API Version
kind: Pod # Object Type
metadata:
  name: yaniv-pod
  labels:
    app: nginx
spec:
  containers:
    - name: animals
      image: supergiantkir/animals:bear
      ports:
        - containerPort: 80
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
    - name: springapp
      image: yanivomc/spring-music:latest
      ports:
        - containerPort: 8080
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
