kind: Service   
apiVersion: v1     
metadata:
  name: my-service 
spec:
  selector:
    app: frontend    # Run on any pod(s) with label - app: myapp
  ports:          # Map incoming port to target port
  - name: animals-http    # Setting multiple ports listterns 
    protocol: TCP
    port: 80
    targetPort: 80
  - name: spring-http
    protocol: TCP
    port: 90
    targetPort: 8080


MISSING PART: TYPE!


