apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  dbname: {{ .Values.database_prod.dbname }}
  dbtable: {{ .Values.database_prod.dbtable }}
  image: {{ .Values.pods.image }}
  tag: {{ .Values.pods.tag }}
  food:
    drink: {{ .Values.food.drink | trim | upper}}
    eat:   {{ .Values.food.eat | trim | upper | trunc 13 | quote }}